name: Publish React Lib to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/react/**'
  workflow_dispatch:

jobs:
  publish:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build package
        run: yarn build-react
      # - name: Run tests
      #   run: yarn test-react
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "packages/react/package.json"
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"