name: Publish Generator Lib to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/generator/**'

jobs:
  publish:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Run tests
        run: yarn test-generator
      - name: Build package
        run: yarn build-generator
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          package: "packages/generator/package.json"
          token: ${{ secrets.NPM_TOKEN }}