name: Test Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Test build docs
        run: yarn build-docs